on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    actions:

    - uses: azure/actions/docker-login@docker
      with:
        loginServer: desattiracr.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
        email: desattir@microsoft.com
    
    - run: |
        docker build . -t desattiracr.azurecr.io/dsmsgosampleapp:latest
        docker push desattiracr.azurecr.io/dsmsgosampleapp:latest 

     - uses: azure/actions/install-kubectl@master
       with:
        version: latest
       id: install
      
    - uses: azure/actions/k8s-set-context@k8s-context
      with:
        kubeconfig: ${{ secrets.KUBECONFIG }}
      id: login

    - uses: azure/actions/k8ssetsecret@master
      with:
        container-registry-url: desattiracr.azurecr.io
        container-registry-username: ${{ secrets.REGISTRY_USERNAME }}
        container-registry-password: ${{ secrets.REGISTRY_PASSWORD }}
        container-registry-email: desattir@microsoft.com
        secret-name: desattiracrsecret
      id: set-secret

    - uses: azure/actions/k8s-deploy@k8s-deploy
      with:
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          desattiracr.azurecr.io/dsmsgosampleapp:latest
        imagepullsecrets: |
          desattiracrsecret
      id: deploy
