on: [push]

jobs:
  build:
    runs-on:
      pool: default
    actions:
    - run: az login --service-principal --username '586a5f0f-3720-42b2-82ef-d4479d53a0a5' --password '/gk+ZqLp7E2PDrzuTvRg0Zju67ExLgAZ0wJisZaV6OM=' --tenant '72f988bf-86f1-41af-91ab-2d7cd011db47'
    - uses: ./webapp-deploy
      with: 
        app-name: linuxwarapp
        package: 'C:/Users/suaggar/Downloads/ROOT.war'
    - uses: ./webapp-deploy
      with: 
        app-name: linuxjarapp
        package: 'C:/Users/suaggar/Downloads/ROOT.jar'
    - uses: ./webapp-deploy
      with: 
        app-name: linuxappsuaggar
        package: 'C:/Users/suaggar/Downloads/phpLaravel'