on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    actions:
    - name: npm install, build, and test
      run: |
        npm install
        npm run build --if-present
        npm run test --if-present
  
    - name: archive myapp
      run: |
        zip -r myapp.zip .
        
    - uses: ./webapp-deploy
      with: 
        publish-profile-path: './linuxappsuaggar.PublishSettings'
        app-name: linuxappsuaggar
        package: './myapp.zip'
      id: myapp-id
    
    # Web app url to work with
    #
    - run: echo "Deployed the webapp at ${{ actions.myapp-id.outputs.webapp-url}}"