on: [push]

jobs:
  build:
    runs-on:
      pool: default
    actions:
    - uses: ./webapp-deploy
      with: 
        app-name: winWebAppTest
        package: "C:\\Users\\suaggar\\Downloads\\AspCore.zip"