
on: [push, pull_request]

env:
  WORKFLOW_LEVEL: "Hello from workflow"
  
permissions: none

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      JOB_LEVEL: "Hello from job"
    steps:
    - run: env
      env:
        STEP_LEVEL: "Hello from step"
  local-action:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./hello-world-action
