
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    actions:
    
    # install dependencies, build, and test
    - name: npm install, build, and test
      run: |
        npm install
        npm run build --if-present
        npm run test --if-present
   
    - name: echo working directory
      run: |
        echo pwd
        echo ls
   
    - uses: ./webapp-deploy
      with: 
        azure-service-app-id: ${{ secrets.AZURE_SERVICE_APP_ID }}
        azure-service-app-key: ${{ secrets.AZURE_SERVICE_APP_KEY }}
        azure-service-tenant-id: ${{ secrets.AZURE_SERVICE_TENANT_ID }}
        azure-subscription: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        app-name: winWebAppTest
        package: './webapp-deploy/TestResources/AspCore.zip'
