on: [push]

jobs:
  build:
    runs-on:
      pool: default
    actions:
    - uses: ./webapp-deploy
      with: 
        azure-service-app-id: ${{ secrets.AZURE_SERVICE_APP_ID }}
        azure-service-app-key: ${{ secrets.AZURE_SERVICE_APP_KEY }}
        azure-service-tenant-id: ${{ secrets.AZURE_SERVICE_TENANT_ID }}
        azure-subscription: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        app-name: winWebAppTest
        package: "TestResources\\AspCore.zip"