on: [push]

jobs:
  build:
    runs-on:
      pool: default
    actions:
    - uses: ./webapp-deploy
      with: 
        app-name: winWebAppTest
        package: './webapp-deploy/TestResources/AspCore'
    - uses: ./webapp-deploy
      with: 
        app-name: winJavaApp
        package: 'C:\USers\suaggar\Downloads\ROOT.war'