
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    actions:
    
    # install dependencies, build, and test
    - name: npm install, build, and test
      run: |
        npm install
        npm run build --if-present
        npm run test --if-present
  
    - name: archive myapp
      run: |
        zip -r myapp.zip .
        
    - uses: ./webapp-deploy
      with: 
        azure-service-app-id: ${{ secrets.AZURE_APP_ID }}
        azure-service-app-key: ${{ secrets.AZURE_APP_KEY }}
        azure-service-tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        azure-subscription: ${{ secrets.SUBSCRIPTION_ID }}
        app-name: node-rn
        package: './myapp.zip'
      id: myapp-id
    
    # Web app url to work with
    - name: Web App url to work with - 
       run: echo "Deployed the webapp at ${{ actions.myapp-id.outputs.webapp-url}}"
