on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image:  node:10.16-jessie
      
    services:
      postgres:
        image: postgres:10.8
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres

      redis:
        image: redis

    actions:        
    - run: echo Hello World change
    - run: docker ps -a
    - run: echo ${{ github.ref }}
    
