
on: [push, pull_request]

env:
  WORKFLOW_LEVEL: "Hello from workflow"
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      JOB_LEVEL: "Hello from job"
    steps:
    - run: env
      env:
        STEP_LEVEL: "Hello from step"
