on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - run: env
    # - uses: azure-login
    #   with:
    #     creds: '${{ secrets.AZURE_CREDENTIALS }}'
    # - run: |
    #     npm install
    #     npm run build --if-present
    #     npm run test --if-present  
    # - run: |
    #     zip -r myapp.zip .        
    # - uses: webapp-deploy
    #   with: 
    #     app-name: node-sa
    #     package: './myapp.zip'
    #   id: myapp-id    
    # - run: echo "Deployed the webapp at ${{ actions.myapp-id.outputs.webapp-url}}"