on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    actions:

    - uses: azure/actions/docker-login@docker
      with:
        acr-name: desattiracr.azurecr.io
        username: ${{ secrets.SPN_ID }}
        password: ${{ secrets.SPN_KEY }}
    
    - run: |
        docker build . -t desattiracr.azurecr.io/dsmsgosampleapp:latest
        docker push desattiracr.azurecr.io/dsmsgosampleapp:latest 

    - uses: azure/actions/k8s-set-context@k8s-context
      with:
        kubeconfig: ${{ secrets.KUBECONFIG }}
      id: login

    - uses: azure/actions/install-kubectl@master
      with:
        version: latest
      id: install

    - run: |
        ${{ actions.install.outputs.kubectlPath }} delete secret desattiracr
        ${{ actions.install.outputs.kubectlPath }} create secret docker-registry desattiracr --docker-server=desattiracr.azurecr.io --docker-username ${{ secrets.SPN_ID }} --docker-password ${{ secrets.SPN_KEY }} --docker-email=abc@example.com

    - uses: azure/actions/k8s-deploy@k8s-deploy
      with:
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          desattiracr.azurecr.io/dsmsgosampleapp:latest
        imagepullsecrets: |
          desattiracr
      id: deploy
