
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    actions:
      - uses: ./k8s-actions/docker-login
        with:
          username: ${{ secrets.CONTAINER_REGISTRY_USERNAME }}
          password: ${{ secrets.CONTAINER_REGISTRY_PASSWORD }}
          loginServer: desattiracr.azurecr.io
          email: abc@example.com
      - run: docker pull desattiracr.azurecr.io/testimage
      - uses: ./k8s-actions/set-context
        with:
          clusterUrl: https://desattiraks-b6ca7c94.hcp.eastus.azmk8s.io
          token: ${{ secrets.KUBERNETES_SERVICE_ACCOUNT_TOKEN }}
          certificate: ${{ secrets.KUBERNETES_SERVICE_ACCOUNT_CERTIFICATE }}
        id: login
      - uses: ./k8s-actions/install-kubectl
        id: install
      - run: ${{ actions.install.outputs.kubectlPath }} version
      - uses: ./k8s-actions/deploy
        with:
          manifests: deployment.yml
        id: deploy