on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
 # working?  
jobs:
  build:
    runs-on: ubuntu-latest
    actions:
    - run: echo Hello World change
    - uses: ./hello-world-action
      with:
        who-to-greet: 'Mundo'
