
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    actions:
    
    # install dependencies, build, and test
    - name: npm install, build, and test
      run: |
        npm install
        npm run build --if-present
        npm run test --if-present
  
    - name: archive myapp
      run: |
        zip -r myapp.zip .
   
    #- name: Login Azure
    # Shell action, will be replaced with first class Azure login action
    #  run: |
    #    az login --service-principal -u ${{ secrets.AZURE_APP_ID }} -p ${{ secrets.AZURE_APP_KEY }} - ${{ secrets.AZURE_TENANT_ID }}
    #    az account set -s ${{ secrets.SUBSCRIPTION_ID }}
        
    - uses: ./webapp-deploy
      with: 
        azure-service-app-id: ${{ secrets.AZURE_APP_ID }}
        azure-service-app-key: ${{ secrets.AZURE_APP_KEY }}
        azure-service-tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        azure-subscription: ${{ secrets.SUBSCRIPTION_ID }}
        app-name: rnnode-win
        package: './myapp.zip'
