on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    actions:

    - uses: azure/actions/docker-login@docker
      with:
        loginServer: desattiracr.azurecr.io
        username: ${{ secrets.SPN_ID }}
        password: ${{ secrets.SPN_KEY }}
        email: desattir@microsoft.com
    
    - run: |
        docker build . -t desattiracr.azurecr.io/dsmsgosampleapp:latest
        docker push desattiracr.azurecr.io/dsmsgosampleapp:latest 

    - uses: azure/actions/k8s-set-context@k8s-context
      with:
        kubeconfig: ${{ secrets.KUBECONFIG }}
      id: login

    - uses: azure/actions/install-kubectl@master
      with:
        version: latest
      id: install

    - uses: azure/actions/k8ssetsecret@master
      with:
        container-registry-url: desattiracr.azurecr.io
        container-registry-username: ${{ secrets.SPN_ID }}
        container-registry-password: ${{ secrets.SPN_KEY }}
        container-registry-email: desattir@microsoft.com
        secret-name: desattiracrsecret
      id: set-secret

    - run: kubectl get secret desattiracrsecret

    - uses: azure/actions/k8ssetsecret@master
      with:
        secret-type: generic       
        secret-name: testsecret
        arguments: '--from-literal=key1=value1 --from-literal=key2="top secret" --from-literal=key3=4'
      id: set-secret

    - run: kubectl get secret testsecret 

    - uses: azure/actions/k8s-deploy@k8s-deploy
      with:
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          desattiracr.azurecr.io/dsmsgosampleapp:latest
        imagepullsecrets: |
          desattiracr
      id: deploy
