on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    actions:
    - run: | 
        az login --service-principal --username ${{ secrets.SPN_ID }} --password ${{ secrets.SPN_KEY }} --tenant ${{ secrets.AZURE_SERVICE_TENANT_ID }}
        az account set -s RMDev

    - uses: azure/actions/acr-login@master
      with:
        acr-name: desattiracr
    
    - run: |
        docker build . -t desattiracr.azurecr.io/sampleapp:$GITHUB_SHA
        docker push desattiracr.azurecr.io/sampleapp:$GITHUB_SHA

    - uses: azure/actions/aks-set-context@users/desattir/aks-set-context
      with:
        resourceGroup: desattiraks-rg
        clusterName: desattiraks
      id: login

    - uses: azure/actions/install-kubectl@master
      with:
        version: latest
      id: install

    - run: ${{ actions.install.outputs.kubectlPath }} delete secret desattiracr
    - run: ${{ actions.install.outputs.kubectlPath }} create secret docker-registry desattiracr --docker-server=desattiracr.azurecr.io --docker-username ${{ secrets.SPN_ID }} --docker-password ${{ secrets.SPN_KEY }} --docker-email=abc@example.com

    - uses: azure/actions/deploy@master
      with:
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          desattiracr.azurecr.io/sampleapp:$(GITHUB_SHA)
        imagepullsecrets: |
          desattiracr
      id: deploy
