on: [push]

jobs:
  build:
    runs-on:
      pool: default
    actions:
    - uses: ./webapp-deploy
      with: 
        app-name: winWebAppTest
        package: 'C:/Users/suaggar/Downloads/AspCore'
    - uses: ./webapp-deploy
      with: 
        app-name: winJavaApp
        package: 'C:/Users/suaggar/Downloads/ROOT.war'
    - uses: ./webapp-deploy
      with: 
        app-name: winJavaApp
        package: 'C:/Users/suaggar/Downloads/ROOT.jar'
    - uses: ./webapp-deploy
      with:
        app-name: linuxappsuaggar
        package: 'C:/Users/suaggar/Downloads/pythonDjango.zip'
    