
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    actions:
    - run: echo Hello World change
    - uses: ./hello-world-action
      with:
        who-to-greet: 'Stephen'
      id: hello
    - run: echo "The time was ${{ actions.hello.outputs.time }}"
    
    - name: Login Azure
      run: |
        az login --service-principal --username ${{ secrets.AZURE_SERVICE_APP_ID }} --password ${{ secrets.AZURE_SERVICE_APP_KEY }} --tenant ${{ secrets.AZURE_SERVICE_TENANT_ID }}

    - name: Show WebApp details
      run: |
        az webapp show --resource-group ronai-dnd --name ronailinux

    - name: Deploy WebApp
      run: |
        az webapp config container set -i ronaiacr.azurecr.io/roopeshnair/example-voting-app:4723 --resource-group ronai-dnd --name ronailinux 
